---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: "Open Port {{ item }}"
  ansible.builtin.iptables:
    chain: "{{ item.protocol | upper }}"
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  loop: "{{ open_iptables_ports_list }}"

- name: Save current state
  community.general.iptables_state:
    state: saved
    path: "{{ iptables_state_file }}"
