---
- name: Install Dependencies
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl

- name: Create keyrings Directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker Repository
  ansible.builtin.copy:
    content: >
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian
      {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
