---
- name: Base Server Setup
  hosts: "{{ target | default('localhost') }}"
  vars:
    user: paco
    ssh_port: 22
  tasks:
    - name: Create User
      ansible.builtin.include_role:
        name: plamendelchev.homelab.create_user
      vars:
        create_user_name: "{{ user }}"
        create_user_password: "*" # Disabled password
      tags:
        - create_user

    - name: Configure SSH
      ansible.builtin.include_role:
        name: plamendelchev.homelab.configure_ssh
      vars:
        configure_ssh_port: "{{ ssh_port }}"
      tags:
        - configure_ssh

    - name: Configure IPTables
      ansible.builtin.include_role:
        name: plamendelchev.homelab.configure_iptables
      vars:
        configure_iptables_open_ports:
          - port: "{{ ssh_port }}"
            protocol: tcp
      tags:
        - configure_iptables

    - name: Install Docker
      ansible.builtin.include_role:
        name: plamendelchev.homelab.install_docker
        apply:
          tags:
            - install_docker
      vars:
        install_docker_user: "{{ user }}"
        install_docker_daemon_config: |
          {
            "storage-driver": "fuse-overlayfs",
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "20m",
              "compress": "true"
            }
          }
      tags:
        - install_docker
